
import pandas as pd
import numpy as np
import os
import shutil
from pathlib import Path

def dump_eth_10m():
    # Source file generated by download_binance_swap.py
    # Assume it's in the same directory as this script
    script_dir = Path(__file__).parent.resolve()
    source_csv = script_dir / 'ETHUSDT_Swap_10m_1y.csv'
    qlib_dir = Path(os.path.expanduser('~/.qlib/qlib_data/crypto_10m'))
    
    if not source_csv.exists():
        print(f"Error: {source_csv} not found. Please run download_binance_swap.py first.")
        return

    print(f"Loading {source_csv}...")
    
    # 1. Load 
    df_10m = pd.read_csv(source_csv)
    df_10m['datetime'] = pd.to_datetime(df_10m['datetime'])
    df_10m = df_10m.set_index('datetime').sort_index()
    
    # Rename quote_volume to amount if present
    if 'quote_volume' in df_10m.columns:
        df_10m = df_10m.rename(columns={'quote_volume': 'amount'})
    
    # Calculate VWAP if missing
    # VWAP approx = Amount / Volume
    if 'vwap' not in df_10m.columns:
        # Avoid division by zero
        df_10m['vwap'] = df_10m['amount'] / df_10m['volume'].replace(0, np.nan)
        df_10m['vwap'] = df_10m['vwap'].fillna(df_10m['close'])
        
    df_10m['factor'] = 1.0
    
    print(f"Data range: {df_10m.index[0]} to {df_10m.index[-1]}")
    print(f"Total bars: {len(df_10m)}")
    
    # 2. Prepare Directories
    if qlib_dir.exists():
        shutil.rmtree(qlib_dir)
    qlib_dir.mkdir(parents=True, exist_ok=True)
    (qlib_dir / 'calendars').mkdir()
    (qlib_dir / 'features').mkdir()
    (qlib_dir / 'instruments').mkdir()
    
    # 3. Calendars
    dates = df_10m.index
    with open(qlib_dir / 'calendars' / 'day.txt', 'w') as f:
        for d in dates:
            f.write(f"{d.strftime('%Y-%m-%d %H:%M:%S')}\n")
            
    # 4. Features
    symbol = 'ethusdt'
    feat_dir = qlib_dir / 'features' / symbol
    feat_dir.mkdir()
    
    # Dump all fields required by Alpha158
    fields = ['open', 'high', 'low', 'close', 'volume', 'amount', 'vwap', 'factor']
    
    for col in fields:
        if col not in df_10m.columns:
            print(f"Warning: {col} missing!")
            continue
            
        # Ensure float32 (Little Endian)
        data = df_10m[col].values.astype('<f4') # <f4 for little endian float32
        
        # Write binary
        bin_path = feat_dir / f"{col.lower()}.day.bin"
        data.tofile(bin_path)
        
    # 5. Instruments
    start_dt = dates[0].strftime('%Y-%m-%d %H:%M:%S')
    end_dt = dates[-1].strftime('%Y-%m-%d %H:%M:%S')
    
    with open(qlib_dir / 'instruments' / 'all.txt', 'w') as f:
        f.write(f"{symbol.upper()}\t{start_dt}\t{end_dt}\n")
        
    print(f"✅ Dumped manually to {qlib_dir}")

if __name__ == "__main__":
    dump_eth_10m()
